pipeline {
    agent any
    stages {
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh "sonar-scanner -Dsonar.java.binaries=./app.jar"
                }
            }
        }
        // stage('SonarQube analysis') {
        //     steps {
        //         withSonarQubeEnv('SonarQube') {
        //             sh "sonar-scanner -Dsonar.java.binaries=target/classes -X"
        //         }
        //     }
        }
    }
}