// pipeline {
//     agent any
//     stages {
//         stage('SCM') {
//             steps {
//                 git 'https://github.com/foo/bar.git'
//             }
//         }

//         stage('Test') {
//             steps {
//                 dir('backend') {
//                     sh './gradlew test'
//                 }
//             }
//         }

//         stage('SonarQube analysis') {
//             steps {
//                 withSonarQubeEnv('sonar') {
//                     dir('backend') {
//                         sh './gradlew sonarqube'
//                     }
//                 }
//             }
//         }
//     }
// }

node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    withSonarQubeEnv() {
      sh "./gradlew sonar"
    }
  }
}