import Head from "next/head";

import { Notifications } from "@/features/notifications";
import { UnauthenticatedLanding } from "@/features/misc";
import { useUser } from "@/features/auth";

export default function Home() {
  const userQuery = useUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {userQuery.isLoading && "Loading..."}
      {userQuery.data && userQuery.data.nickname.length === 0 && (
        <UnauthenticatedLanding />
      )}
      {userQuery.data && userQuery.data.nickname.length !== 0 && (
        <Notifications />
      )}
    </>
  );
}
