import Head from "next/head";
import { Projects } from "@/features/projects";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { useRouter } from "next/router";

export default function Project() {
  const queryClient = new QueryClient();
  const router = useRouter();
  console.log(typeof router.pathname.slice(1));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueryClientProvider client={queryClient}>
        <Projects />
      </QueryClientProvider>
    </>
  );
}
