import { useRouter } from "next/router";
import { useEffect } from "react";

import { useAsPathInfoStore } from "@/stores";
import { useSearchCriteriaStore } from "@/stores";

import Head from "next/head";
import { Projects } from "@/features/projects";

export default function Project() {
  const { asPath } = useRouter();
  const { asPathInfo, setAsPath } = useAsPathInfoStore();
  const { reset } = useSearchCriteriaStore();

  useEffect(() => {
    if (asPathInfo.currentAsPath !== asPath) {
      setAsPath(asPath, asPathInfo.currentAsPath);
    }
    if (
      (asPathInfo.prevAsPath === "/project" &&
        asPathInfo.currentAsPath === "/code-review") ||
      (asPathInfo.prevAsPath === "/code-review" &&
        asPathInfo.currentAsPath === "/project")
    ) {
      reset();
    }
  }, [asPath, asPathInfo.currentAsPath]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Projects />
    </>
  );
}
